# This file is just an example and should not be used in production

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-api-server-template
  labels:
    app: ts-api-server-template
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ts-api-server-template
  template:
    metadata:
      labels:
        app: ts-api-server-template
    spec:
      containers:
      - name: ts-api-server-template
        image: ts-api-server-template
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        livenessProbe:
          httpGet:
            port: 8080
            path: health-check
          initialDelaySeconds: 5
          periodSeconds: 1
          failureThreshold: 1